import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

// TO BE DONE BY: Jannson
// This is the landing page for the app. It should be the first page that the user sees when they visit the site.
// The page can be accessed at http://localhost:3000/landing

const LandingPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Taskmate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen items-center justify-center ">
        {/* YOUR CONTENT GOES BETWEEN HERE */}
        <p className="text-9xl">@Jann make nice nice</p>
        {/* YOUR CONTENT GOES BETWEEN HERE */}
      </div>
    </>
  );
};

export default LandingPage;
